TRUNCATE TABLE users RESTART IDENTITY CASCADE;
TRUNCATE TABLE wall RESTART IDENTITY CASCADE;
TRUNCATE TABLE private_messages RESTART IDENTITY CASCADE;
TRUNCATE TABLE public_messages RESTART IDENTITY CASCADE;
TRUNCATE TABLE community RESTART IDENTITY CASCADE;
TRUNCATE TABLE friend_request RESTART IDENTITY CASCADE;
TRUNCATE TABLE group_chat RESTART IDENTITY CASCADE;
